#!/usr/bin/php
<?php

declare(strict_types=1);

use System\Cli\Cli;

if (php_sapi_name() !== 'cli') {
   exit('CLI only');
}
chdir(__DIR__);

require_once __DIR__ . "/App/Config/Constants.php";
require_once __DIR__ . "/vendor/autoload.php";

foreach (glob(SYSTEM_DIR . "Helpers/*.php") as $filename) {
   require_once $filename;
}

$params = array_slice($argv, 1);

$cli = new Cli();
echo $cli->run($params);
