#!usr/bin/php
<?php

declare(strict_types=1);

use System\Cli\Cli;

// Requires
require_once __DIR__ . "/App/Config/Constants.php";
require_once __DIR__ . "/vendor/autoload.php";
foreach (glob(__DIR__ . "/System/Helpers/*.php") as $filename) {
   require_once $filename;
}

$params = array_slice($argv, 1);
$cli = new Cli();
print($cli->run($params));
